services:
  web:
    build: ./flask_app
    volumes:
      - ./flask_app:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password@db/flask_db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_db
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build: ./nginx
    ports:
      - "5000:80" # Map port 5000 on the host to port 80 in the Nginx container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  mysql-data:
